language: ruby
rvm:
- 2.2.0
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_6371fc667431_key -iv $encrypted_6371fc667431_iv
  -in octpus.enc -out octpus -d
env:
  global:
  - secure: ZRGB33f41my5smKtusJYoaQp+4IcOaogpLUPvVWuGl1ty88D0pxMt/tgzm/Md3uoBrfixmlIV9GDF4LoRw5mb0qQ9iunKyaciwItxxPbQChcnrxATZGwRsW4L/WxuRZh5MP8siwpkItMaarM+yDe/yzTGc5B09nJ8XEZdjE0cCM=
  - secure: XVY6espWrdQeplf0JbGbq/LoQzRHOKTUeIL4VMT3LVZT8eZ2k+JZ611nbaH89S7keeciwLKPAU64uYWw8Ad/XYuoy00ec2b2i5uIcCyHRsEHcq/V6DGyeysOAZnAke4Q7QIsvZtbsaVCH+yW88UAhABq5LJuRkvjC+XV0UHiGYs=
  - secure: m0mVcPjEPt+Bog/ES4XnVSDTvE/+bpzzsqLr3A/vS09LGUNkJV1evCRtYCQpNvvbHjNx+9PAbeQesoJ0xUufoed5cc29YvY4MfITgMJFe7UzRnpNqZ+1Qydic8smncKi+ACqD+oS9m3krPijMryb+nBiJwZGb5rxMk10ZPpFMao=
  - secure: ukzbzJopoYoYESMPd3ABzSFCNbs1V8mH18WcUjvdSH55v8lkWXI5R/vyJ+IF6c2ndzpGotFTFqW3AXk8Kf90bvMeXmQMr49DLh5zIwvDLG+WB3J0/oq326DtHVXm2PQ0hjx7PYWJB909TftrcTeL65M5BZFlkzZ6PKnknlQlGNI=
script: bundle exec itamae ssh -h $host -p $port -u octpus -i octpus -y octpus.yml
  recipe.rb
